### ISSUE TITLE
About the dataset PACS

### ISSUE THREAD

**Issue by QiyuanY** [MediaBrain-SJTU/FedDG-GA#1]
Hello, thanks for your pretty good work firstly. But when I try to reproduce the training, I find that the origin download link of  PACS dataset is valid,  could you please release your dataset, it's a little difficult for me to make the standard dataset to fit this work. Thanks a lot!

**Comment by FrankZhangRp** [comment]
Hello, thank you for finding this issue. The download of the PACS dataset can be found in the facebookresearch/DomainBed project, and the specific download address is: https://drive.google.com/uc?id=1JFr8f805nMUelQWWmfnJR3y4_SYoN5Pd. I hope this can help you reproduce the training process. If you have any other questions, please feel free to ask.
