### ISSUE TITLE
photo_train_kfold.txt

### ISSUE THREAD

**Issue by QiyuanY** [MediaBrain-SJTU/FedDG-GA#2]
Sorry to bother your again, but when I run the code , it shows error as fig shown. I think this means I need to split dataset into train,val,test addtionally, right? How can I pre-processing the PACS? Could you please show me one sample or tutorial. I can't access your paper via openreview.net. Hope to recieve your reply and thanks for your time! 
![1{8ZG`0WZ`CXPPNU) 72JDM](https://user-images.githubusercontent.com/73385315/230344754-6a74fe2d-d4a0-479c-8120-1e4e87015c32.png)

**Comment by ragjapk** [comment]
These files are available here: https://github.com/DeLightCMU/RSC/tree/master/Domain_Generalization/data/correct_txt_lists
