### ISSUE TITLE
关于generalization gaps的计算

### ISSUE THREAD

**Issue by QiyuanY** [MediaBrain-SJTU/FedDG-GA#3]
在论文中的计算是两个风险函数在本地训练过程中相减得到的一个结果，但是在代码中只看到了classification这个对象的acc和loss输出，请问这个相减的式子在代码中是如何体现的呢？

**Comment by FrankZhangRp** [comment]
因为实验过程中是模拟的通信，因此我们用“refine_weight_dict_by_GA”函数实现了整个gap计算+权重更新的过程。基于GA方法的新code会更加简洁，等相关文章中稿后也会第一时间开源代码，届时整个流程会更加清晰。
