### ISSUE TITLE
第4页左栏第一个公式的疑问

### ISSUE THREAD

**Issue by ShaneSpace** [MediaBrain-SJTU/FedDG-GA#5]
作者你好，
第4页左栏第一个公式写的是
\theta = \theta_k + \delta \theta
但是 \delta \theta是不是应该等于 (a_k-1)\theta_k +\sum_{i\neq k}a_i\theta_i呢？

**Comment by FrankZhangRp** [comment]
嗯是的，不好意思我们这里的公式出现了一个笔误。
